# Generated by Django 4.2 on 2023-06-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Stage', models.CharField(blank=True, max_length=100, null=True)),
                ('Agromet_Advisory', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Layers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensorproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('device_id', models.CharField(max_length=255)),
                ('sensor_type', models.CharField(choices=[('Soil sensor', 'Soil Sensor'), ('Weather sensor', 'Weather Sensor')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Battery', models.FloatField(blank=True, null=True)),
                ('EC_S1', models.FloatField(blank=True, null=True)),
                ('EC_S2', models.FloatField(blank=True, null=True)),
                ('Moisture_S1_P', models.FloatField(blank=True, null=True)),
                ('Moisture_S2_P', models.FloatField(blank=True, null=True)),
                ('Temperature_S1_P', models.FloatField(blank=True, null=True)),
                ('Temperature_S2_P', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sensor_Sensorproperty', to='sensors.sensorproperty')),
            ],
        ),
    ]
