# Generated by Django 4.2 on 2023-06-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensorproperty',
            new_name='devices',
        ),
        migrations.RenameModel(
            old_name='Sensor',
            new_name='SoilSensor',
        ),
    ]
