# Generated by Django 4.2 on 2023-06-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_rename_sensorproperty_devices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
                ('Wind_dir', models.FloatField()),
                ('Solar_rad', models.FloatField()),
                ('Leaf_up', models.FloatField()),
                ('Leaf_down', models.FloatField()),
                ('Battery_voltage', models.FloatField()),
                ('Voltage_power_supply', models.FloatField()),
                ('Wind_speed', models.FloatField()),
                ('Wind_gust', models.FloatField()),
                ('Max_rain', models.FloatField()),
                ('Daily_rain', models.FloatField()),
                ('Rain_counter', models.FloatField()),
                ('Temperature', models.FloatField()),
                ('Relative_Humidity', models.FloatField()),
                ('Dew_point', models.FloatField()),
                ('Soil_temp', models.FloatField()),
            ],
        ),
    ]
