# Generated by Django 4.2 on 2023-06-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_weathersensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathersensor',
            name='Battery_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Daily_rain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Dew_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Leaf_down',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Leaf_up',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Max_rain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Rain_counter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Relative_Humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Soil_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Solar_rad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Voltage_power_supply',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Wind_dir',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Wind_gust',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersensor',
            name='Wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
