# Generated by Django 4.2 on 2023-06-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_alter_weathersensor_battery_voltage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilsensor',
            old_name='Moisture_S1_P',
            new_name='Moisture_S1',
        ),
        migrations.RenameField(
            model_name='soilsensor',
            old_name='Moisture_S2_P',
            new_name='Moisture_S2',
        ),
        migrations.RenameField(
            model_name='soilsensor',
            old_name='Temperature_S1_P',
            new_name='Temperature_S1',
        ),
        migrations.RenameField(
            model_name='soilsensor',
            old_name='Temperature_S2_P',
            new_name='Temperature_S2',
        ),
        migrations.AddField(
            model_name='soilsensor',
            name='Timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
