# Generated by Django 4.2 on 2023-06-24 09:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_weathersensor_water_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soilsensor',
            old_name='property',
            new_name='devices',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='longitude',
        ),
        migrations.AddField(
            model_name='devices',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='devices',
            name='sensor_type',
            field=models.CharField(choices=[('Soil Sensor', 'Soil Sensor'), ('Weather Sensor', 'Weather Sensor')], max_length=255),
        ),
    ]
