# Generated by Django 4.2 on 2023-06-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_alter_devices_device_id_alter_soilsensor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weathersensor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
