# Generated by Django 4.2 on 2023-06-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_devices_created_at_layers_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
