# Generated by Django 4.2 on 2023-07-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0011_alter_advisory_created_at_alter_devices_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilsensor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
