# Generated by Django 4.2 on 2023-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0012_alter_soilsensor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilsensor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
