# Generated by Django 4.1.6 on 2023-07-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0013_alter_soilsensor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='Advisory_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
