# Generated by Django 4.1.6 on 2023-07-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0017_alter_advisory_advisory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilsensor',
            name='Raw_S1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soilsensor',
            name='Raw_S2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
