# Generated by Django 4.1.6 on 2023-07-01 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nmscdcl_services', '0009_delete_shp_datastore_created_date_and_more'),
        ('nmscdcl_filemanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=300)),
                ('creationMode', models.CharField(choices=[('CREATE', 'CREATE'), ('APPEND', 'APPEND'), ('OVERWRITE', 'OVERWRITE')], max_length=50)),
                ('name', models.CharField(max_length=300)),
                ('layerName', models.CharField(max_length=300)),
                ('encoding', models.CharField(max_length=100)),
                ('srs', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExportUser', to=settings.AUTH_USER_MODEL)),
                ('datastore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataSource', to='nmscdcl_services.datastore')),
            ],
        ),
    ]
