# Generated by Django 4.1.6 on 2023-07-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmscdcl_filemanager', '0002_exporthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporthistory',
            name='encoding',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exporthistory',
            name='srs',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
