# Generated by Django 4.1.6 on 2023-02-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='shp/')),
                ('mode', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('encoding', models.CharField(max_length=20)),
                ('srs', models.TextField()),
            ],
        ),
    ]
