# Generated by Django 4.1.6 on 2023-02-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmscdcl_services', '0002_shp_connection_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shp',
            name='connection_params',
            field=models.JSONField(default=dict),
        ),
    ]
