# Generated by Django 4.1.6 on 2023-02-22 10:24

from django.db import migrations, models
import django.db.models.deletion
import nmscdcl_services.models


class Migration(migrations.Migration):

    dependencies = [
        ('nmscdcl_services', '0004_server_alter_shp_connection_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datastore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('connection_params', models.TextField()),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LayerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.IntegerField(default=nmscdcl_services.models.get_default_server, null=True)),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('cached', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('uri', models.CharField(max_length=500)),
                ('wms_endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('wfs_endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('wcs_endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('wmts_endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('cache_endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(default=nmscdcl_services.models.get_default_server, on_delete=django.db.models.deletion.CASCADE, related_name='WorkspaceServer', to='nmscdcl_services.server')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external', models.BooleanField(default=False)),
                ('external_params', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('abstract', models.CharField(blank=True, max_length=5000, null=True)),
                ('type', models.CharField(max_length=150)),
                ('public', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('queryable', models.BooleanField(default=True)),
                ('cached', models.BooleanField(default=False)),
                ('single_image', models.BooleanField(default=False)),
                ('vector_tile', models.BooleanField(default=False)),
                ('allow_download', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=100)),
                ('created_by', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('timeout', models.IntegerField(default=30000, null=True)),
                ('native_srs', models.CharField(default='EPSG:4326', max_length=100)),
                ('native_extent', models.CharField(default='-180,-90,180,90', max_length=250)),
                ('latlong_extent', models.CharField(default='-180,-90,180,90', max_length=250)),
                ('source_name', models.TextField(blank=True, null=True)),
                ('datastore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nmscdcl_services.datastore')),
                ('layer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmscdcl_services.layergroup')),
            ],
        ),
        migrations.AddField(
            model_name='datastore',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmscdcl_services.workspace'),
        ),
    ]
