# Generated by Django 4.1.6 on 2023-03-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmscdcl_services', '0006_alter_datastore_connection_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='connection_params',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='type',
            field=models.CharField(choices=[('POSTGIS', 'POSTGIS'), ('c_GeoTIFF', 'c_GeoTIFF')], max_length=250),
        ),
    ]
