# Generated by Django 4.1.6 on 2023-04-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmscdcl_services', '0007_alter_datastore_connection_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='layergroup',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
