# Generated by Django 4.1.6 on 2023-06-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmscdcl_services', '0008_alter_layer_name_alter_layergroup_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SHP',
        ),
        migrations.AddField(
            model_name='datastore',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='datastore',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datastore',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layer',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='layergroup',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='layergroup',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='layergroup',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='server',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
