# Generated by Django 4.1.6 on 2023-07-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmscdcl_services', '0009_delete_shp_datastore_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='name',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='type',
            field=models.CharField(choices=[('v_PostGIS', 'v_PostGIS'), ('c_GeoTIFF', 'c_GeoTIFF')], max_length=250),
        ),
    ]
